"""
PLOYMORPHISM
(UNKNOWN USES :
    LOOSE COUPLING
    DEPENDENCY INJECTION
    INTERFACE)
TYPES OF IMPEMENTATION
    DUCK TYPING
    OPERATOR OVERLOADING
    METHOD OVERLOADING
    METHOD OVERRIDING
"""

# POLYMORPHISM MEANS ONE THING THAT WORKS IN DIFFERENT FORMS
