import DSA.LINKEDLIST.single_end_linked_list as ds

ll = ds.Linked_List()
print(ll)
ll.insert_at_the_beginning(45)
ll.insert_at_the_beginning(23)
ll.insert_at_the_beginning(34)
ll.insert_at_the_beginning(56)
ll.insert_at_the_beginning(234)
ll.insert_at_the_beginning(374)
ll.insert_at_the_beginning(356)
ll.insert_at_the_beginning(223)
ll.insert_at_the_beginning(345)
ll.insert_at_the_beginning(566)
ll.insert_at_the_beginning(235)
ll.insert_at_the_beginning(354)
ll.insert_at_the_beginning(586)
ll.insert_at_the_beginning(263)
ll.insert_at_the_beginning(344)
ll.insert_at_the_beginning(956)
ll.insert_at_the_beginning(354)
ll.insert_at_the_beginning(586)
ll.insert_at_the_beginning(263)
ll.insert_at_the_beginning(344)
ll.insert_at_the_beginning(956)
ll.print_all()
ll.delete_top_element()
ll.delete_top_element()
ll.delete_top_element()
ll.delete_top_element()
ll.delete_bottom_element()
ll.delete_bottom_element()
ll.delete_bottom_element()
ll.delete_bottom_element()
ll.delete_bottom_element()
ll.print_all()
print("tyftyf")
ll.print_again()
